# Generated by Django 6.0.4 on 2026-04-08 07:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=50, unique=True, verbose_name='Sigla Raqami')),
                ('familiya', models.CharField(max_length=200, verbose_name='Familiya')),
                ('toifa', models.CharField(choices=[('gazeta', 'Gazeta'), ('jurnal', 'Jurnal'), ('0', '0 - Fan, Texno, Kutub'), ('1', '1 - Falsafa, Psixologiya'), ('2', '2 - Din'), ('3', '3 - Ijtimoiy Fanlar'), ('5', '5 - Matematika va Tabiiy Fanlar'), ('6', '6 - Amaliy Fanlar, Tibbiyot, Texnologiya'), ('7', "7 - San'at, Sport"), ('8', '8 - Til, Adabiyot'), ('9', '9 - Geografiya, Tarix')], max_length=20, verbose_name='Toifa')),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan Sanasi")),
                ('yosh', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yoshi')),
                ('yangi_avo_sana', models.DateField(default=datetime.date.today, verbose_name="Yangi A'zo Bo'lgan Sana")),
                ('qayta_avo_sana', models.DateField(blank=True, null=True, verbose_name="Qayta A'zo Bo'lgan Sana")),
                ('holati', models.CharField(choices=[('faol', 'Faol'), ('faol_emas', 'Faol emas')], default='faol', max_length=20, verbose_name='Holati')),
                ('azolik_bosh', models.DateField(blank=True, null=True, verbose_name="A'zolik Boshlanish Sanasi")),
                ('azolik_tug', models.DateField(blank=True, null=True, verbose_name="A'zolik Tugash Sanasi")),
                ('tolov_summa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="To'lov Summasi")),
                ('tolov_sana', models.DateField(blank=True, null=True, verbose_name="To'lov Sanasi")),
                ('tolov_turi', models.CharField(blank=True, choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('online', 'Online')], max_length=20, null=True, verbose_name="To'lov Turi")),
                ('cat_gazeta', models.PositiveIntegerField(default=0)),
                ('cat_jurnal', models.PositiveIntegerField(default=0)),
                ('cat_0', models.PositiveIntegerField(default=0)),
                ('cat_1', models.PositiveIntegerField(default=0)),
                ('cat_2', models.PositiveIntegerField(default=0)),
                ('cat_3', models.PositiveIntegerField(default=0)),
                ('cat_5', models.PositiveIntegerField(default=0)),
                ('cat_6', models.PositiveIntegerField(default=0)),
                ('cat_7', models.PositiveIntegerField(default=0)),
                ('cat_8', models.PositiveIntegerField(default=0)),
                ('cat_9', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "A'zo",
                'verbose_name_plural': "A'zolar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=300, verbose_name='Kitob Nomi')),
                ('category', models.CharField(choices=[('gazeta', 'Gazeta'), ('jurnal', 'Jurnal'), ('0', '0 - Fan, Texno, Kutub'), ('1', '1 - Falsafa, Psixologiya'), ('2', '2 - Din'), ('3', '3 - Ijtimoiy Fanlar'), ('5', '5 - Matematika va Tabiiy Fanlar'), ('6', '6 - Amaliy Fanlar, Tibbiyot, Texnologiya'), ('7', "7 - San'at, Sport"), ('8', '8 - Til, Adabiyot'), ('9', '9 - Geografiya, Tarix')], max_length=20, verbose_name='Kategoriya')),
                ('berilgan_sana', models.DateField(default=datetime.date.today, verbose_name='Berilgan Sana')),
                ('qaytarish_sana', models.DateField(verbose_name='Qaytarish Sanasi')),
                ('qaytarildi', models.BooleanField(default=False, verbose_name='Qaytarildi')),
                ('qaytarilgan_sana', models.DateField(blank=True, null=True, verbose_name='Qaytarilgan Sana')),
                ('jarima_kun_narxi', models.DecimalField(decimal_places=2, default=500, max_digits=8, verbose_name='Jarima (1 kun)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issues', to='core.member')),
            ],
            options={
                'verbose_name': 'Kitob Berish',
                'verbose_name_plural': 'Kitob Berish Jurnali',
                'ordering': ['-berilgan_sana'],
            },
        ),
    ]
