# Generated by Django 6.0.4 on 2026-04-16 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_chat_id_member_telegram_id_alter_member_sigla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Kitob Nomi')),
                ('author', models.CharField(max_length=300, verbose_name='Muallif')),
                ('category', models.CharField(choices=[('gazeta', 'Gazeta'), ('jurnal', 'Jurnal'), ('0', '0 - Fan, Texno, Kutub'), ('1', '1 - Falsafa, Psixologiya'), ('2', '2 - Din'), ('3', '3 - Ijtimoiy Fanlar'), ('5', '5 - Matematika va Tabiiy Fanlar'), ('6', '6 - Amaliy Fanlar, Tibbiyot, Texnologiya'), ('7', "7 - San'at, Sport"), ('8', '8 - Til, Adabiyot'), ('9', '9 - Geografiya, Tarix')], max_length=20, verbose_name='Kategoriya')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Umumiy Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kitob (Katalog)',
                'verbose_name_plural': 'Kitoblar (Katalog)',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Filial Nomi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file_url', models.FileField(upload_to='ebooks/')),
                ('access_type', models.CharField(choices=[('free', 'Bepul'), ('paid', 'Pullik')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Elektron Kitob',
                'verbose_name_plural': 'Elektron Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Shtrix-kod')),
                ('status', models.CharField(choices=[('available', 'Mavjud'), ('borrowed', 'Olingan'), ('lost', "Yo'qolgan"), ('damaged', 'Shikastlangan')], default='available', max_length=20, verbose_name='Holati')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.book')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='core.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Kitob Nusxasi',
                'verbose_name_plural': 'Kitob Nusxalari',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.branch', verbose_name='Filial'),
        ),
        migrations.CreateModel(
            name='EbookReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='core.ebook')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_reads', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('ready', 'Tayyor'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='waiting', max_length=20)),
                ('queue_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_until', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.member')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['queue_order', 'created_at'],
            },
        ),
    ]
