# Generated by Django 6.0.4 on 2026-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_branch_ebook_bookitem_member_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nashr yili'),
        ),
    ]
