# Generated by Django 6.0.4 on 2026-07-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='book_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='core.bookitem', verbose_name='Kitob Nusxasi'),
        ),
    ]
