# Generated by Django 6.0.4 on 2026-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bookissue_book_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Foydalanuvchi/Kutubxonachi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('browser', models.CharField(blank=True, max_length=300, null=True, verbose_name='Brauzer')),
                ('action', models.CharField(max_length=200, verbose_name='Amal')),
                ('module', models.CharField(max_length=100, verbose_name='Modul')),
                ('result', models.CharField(default='success', max_length=200, verbose_name='Natija')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Loglar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300, verbose_name='Fayl nomi')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Avtomatik zaxira')),
            ],
            options={
                'verbose_name': 'Zaxira nusxasi',
                'verbose_name_plural': 'Zaxira nusxalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Sabab va izoh')),
                ('requested_days', models.PositiveIntegerField(default=7, verbose_name="So'ralgan kunlar")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan sana")),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='core.bookissue', verbose_name='Kitob Berish yozuvi')),
            ],
            options={
                'verbose_name': "Muddat uzaytirish so'rovi",
                'verbose_name_plural': "Muddat uzaytirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
