# Generated by Django 6.0.4 on 2026-07-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog_backuplog_extensionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cat_0',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_3',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_5',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_6',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_7',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_8',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_9',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_gazeta',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cat_jurnal',
        ),
    ]
