# Generated by Django 6.0.4 on 2026-07-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_member_cat_0_remove_member_cat_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='member',
            name='toifa',
        ),
        migrations.AlterField(
            model_name='member',
            name='holati',
            field=models.CharField(choices=[('faol', 'Faol'), ('faol_emas', 'Faol emas'), ('kutilmoqda', 'Kutilmoqda')], default='faol', max_length=20, verbose_name='Holati'),
        ),
    ]
