# Generated by Django 6.0.7 on 2026-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_book_category_remove_bookissue_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='barcode',
            field=models.CharField(max_length=100, verbose_name='Inventar raqami'),
        ),
    ]
