# Generated by Django 6.0.7 on 2026-07-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reservation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionrequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True, verbose_name="So'ralgan muddat (Sana)"),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Parol'),
        ),
        migrations.AddField(
            model_name='member',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiklash Kodi'),
        ),
        migrations.AddField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Username'),
        ),
        migrations.AddField(
            model_name='member',
            name='yunalish',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Yo'nalishi"),
        ),
    ]
