# Generated by Django 5.2.16 on 2026-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_extensionrequest_requested_date_member_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionrequest',
            name='admin_message',
            field=models.TextField(blank=True, null=True, verbose_name='Admin javobi/sababi'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Sigla Raqam'),
        ),
    ]
