# Generated by Django 5.2.16 on 2026-09-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_extensionrequest_admin_message_alter_member_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron Pochta'),
        ),
    ]
