# Generated by Django 5.2.16 on 2026-09-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yosh toifasi'),
        ),
        migrations.AddField(
            model_name='book',
            name='bbk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BBK'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='Badiiy adabiyot', max_length=150, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif / Annotatsiya'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Janr'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name="Kalit so'zlar"),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default="O'zbek", max_length=50, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf_location',
            field=models.CharField(default='Javon A-1', max_length=100, verbose_name='Javon joylashuvi'),
        ),
        migrations.AddField(
            model_name='book',
            name='target_audience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maqsadli auditoriya'),
        ),
        migrations.AddField(
            model_name='book',
            name='udk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UDK'),
        ),
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_json', models.TextField(blank=True, null=True, verbose_name='Embedding vektori (JSON)')),
                ('indexed_text', models.TextField(blank=True, null=True, verbose_name='Indekslangan matn')),
                ('last_indexed', models.DateTimeField(auto_now=True, verbose_name='Oxirgi indekslash')),
                ('status', models.CharField(default='ready', max_length=20, verbose_name='Holati')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.book')),
            ],
            options={
                'verbose_name': 'Kitob Embeddingi',
                'verbose_name_plural': 'Kitob Embeddinglari',
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Yoqdi'), ('dislike', 'Qiziq emas'), ('rating', 'Reyting')], max_length=20, verbose_name='Turi')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reyting (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Fikr')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.book', verbose_name='Kitob')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to='core.member', verbose_name='Kitobxon')),
            ],
            options={
                'verbose_name': 'Tavsiya munosabati',
                'verbose_name_plural': 'Tavsiya munosabatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name="Qidiruv so'rovi")),
                ('normalized_query', models.CharField(blank=True, max_length=500, verbose_name='Normalizatsiya qilingan')),
                ('results_count', models.IntegerField(default=0, verbose_name='Natijalar soni')),
                ('search_mode', models.CharField(default='hybrid', max_length=50, verbose_name='Qidiruv rejimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='core.member', verbose_name='Kitobxon')),
            ],
            options={
                'verbose_name': 'Qidiruv jurnali',
                'verbose_name_plural': 'Qidiruv jurnallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
